// Try...Catch
    // It is used for error handling

    try{
        console.log(string.toUpperCase());
    } catch {
        console.log("Look out for the Error!!!!!")
    }
    console.log("It works despite the Error"  )
    